version: '3.8'
name: capacitaciones-m-prod

services:
  db:
    image: mysql:8.0
    container_name: capacitaciones-m-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    env_file:
      - .env
    ports:
      - "127.0.0.1:3351:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - capacitaciones-m

  api:
    image: ghcr.io/inntek15dev-lang/capacitaciones-m-api:latest
    container_name: capacitaciones-m-api
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER={DB_USER}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - FRONT_URL=${FRONT_URL}
    env_file:
      - .env
    ports:
      - "127.0.0.1:4051:4051"
    depends_on:
      - db
    networks:
      - capacitaciones-m

  frontend:
    image: ghcr.io/inntek15dev-lang/capacitaciones-m-front:latest
    container_name: capacitaciones-m-front
    restart: always
    environment:
      - VITE_API_URL=https://capacitaciones-m-api.ovalcontrol.com/api/v1
    ports:
      - "127.0.0.1:8051:80"
    depends_on:
      - api
    networks:
      - capacitaciones-m

networks:
  capacitaciones-m:
    driver: bridge
