# Etapa 1: Build
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Ajustes Nginx para SPA
RUN sed -i '10i \\n    location / {\n        try_files $uri /index.html;\n    }\n' /etc/nginx/conf.d/default.conf

# Script para inyectar variables en runtime
COPY env.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/env.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
